- name: Hello World Sample
  hosts: all
  gather_facts: no
  connection: local
  tasks:
    - name: Show java variables
      debug:
        msg: "{{ java_home }}"
    - name: show me weblogic variables
      debug:
        msg: "{{ weblogic_home }}"

